Add command shell to create Action File
HavokInspiration/cakephp-actions-class pull request #2
Opened 2017-08-10 09:12 UTC by EdouardTack

This is a shell to add command line to create Action File like Cake Bake.

2017-08-10 11:13 UTC, HavokInspiration requested changes
Hi and thanks a lot for this contribution ! 😄 

Being able to create an Action class from the command line is definitively going to be a very nice addition ! 👍 

However, it should use the `bake` command tool and not a "raw" shell.
See my comment on the `ActionShell` file for more details.

2017-08-10 11:13 UTC, HavokInspiration commented on src/Shell/ActionShell.php
> +class ActionShell extends Shell
You should create a `Task` class (under Shell/Task) that extends `SimpleBakeTask` from the `Bake` plugin instead of creating a Shell.
It has a lot of utility methods for creating files, creating the test(s) file(s), managing the `plugin` option (which is supported out of the box by the Options Parser and also have utility methods to be managed if I remember correctly), etc. that you would not have had to write.

Basically, the Action file should be created using the following command :
```
bin/cake bake action Posts/Index
```
where `Posts` is the controller name and `Index` the action name (and with options `plugin` and `prefix` available as you did here).

As for the prefix management, you could inspire yourself from the `ControllerTask`  bundle with with `bake` : https://github.com/cakephp/bake/blob/master/src/Shell/Task/ControllerTask.php#L105-L108

You can find an example of a custom bake task here on another project I made : https://github.com/HavokInspiration/wrench/blob/master/src/Shell/Task/MaintenanceModeTask.php

If you need further guidance to implement this, you can reach out to me on the CakePHP's Slack channels by PM (I have the same nickname 😉 ) or we can do it in this PR.

2017-08-10 14:28 UTC, EdouardTack commented
Thanks for review. I will check this out and review my code.

2017-08-11 15:47 UTC, HavokInspiration requested changes
There are a lot of indentation problems and I have concerns about the directory in which the ActionTest file will be created.

We are going to need some tests as well (I can take care of that if you want).

Other than that this is looking good !

2017-08-11 15:47 UTC, HavokInspiration commented on src/Shell/Task/ActionTask.php
> +	/**
Indentation is off

2017-08-11 15:47 UTC, HavokInspiration commented on src/Shell/Task/ActionTask.php
> +	];
Indentation is off (4 spaces)

2017-08-11 15:47 UTC, HavokInspiration commented on src/Shell/Task/ActionTask.php
> +		'Bake.BakeTemplate'
Indentation is off (4 spaces)

2017-08-11 15:47 UTC, HavokInspiration commented on src/Shell/Task/ActionTask.php
> +        return 'file for HavokInspiration/ActionsClass';
I'd rather have "action" here only

2017-08-11 15:47 UTC, HavokInspiration commented on src/Shell/Task/ActionTask.php
> +	    	list($controller, $action) = explode('/', $name);
Indentation is off

2017-08-11 15:47 UTC, HavokInspiration commented on src/Shell/Task/ActionTask.php
> +    		$action = 'index';
Indentation is off

2017-08-11 15:47 UTC, HavokInspiration commented on src/Shell/Task/ActionTask.php
> +		$action = $this->_camelize($action);
Indentation is off

2017-08-11 15:47 UTC, HavokInspiration commented on src/Shell/Task/ActionTask.php
> +    	$prefix = $this->_getPrefix();
Indentation is off somewhere for the 4 above lines

2017-08-11 15:47 UTC, HavokInspiration commented on src/Shell/Task/ActionTask.php
> +        ];
Indentation is off (and only one space between `'` and `=>`. They should not be aligned they tend to be out of sync really quickly.

2017-08-11 15:47 UTC, HavokInspiration commented on src/Shell/Task/ActionTask.php
> +            sprintf('Bake a %s.', $name)
The sentence here can be hard coded. "Bake an Action class"

2017-08-11 15:47 UTC, HavokInspiration commented on src/Shell/Task/ActionTask.php
> +        $this->_createTestFile(TESTS . 'TestCase' . DS . 'Controller' . DS . $controller . DS . $action . 'Action.php');
Will this test file be created in the good directory ? I mean if there is a prefix or a plugin used ?

2017-08-11 15:48 UTC, HavokInspiration commented
I can take care of the PHPStan errors as well.

2017-08-11 15:57 UTC, HavokInspiration commented on src/Shell/Task/ActionTask.php
> +    }
You should use the BakeTest task instead.

2017-08-17 07:05 UTC, EdouardTack commented
If you can do the Tests and PHPStan errors, i will appreciate. I do'nt feel comfortable with that.
This will allow me to see how to do the tests with Bake plugin.

2017-08-25 16:46 UTC, HavokInspiration commented
Hi. Sorry about the long silence, I was on vacation. I'll take care of finishing the work on this pull request as soon as I can.

2017-08-28 21:20 UTC, HavokInspiration commented
I pushed a few commits to refactor the task a bit and add tests and better PHPStan management.

2017-08-28 21:21 UTC, merged

2017-08-28 21:21 UTC, HavokInspiration commented
Merged ! Thanks a lot for your contribution. I will tag a new release.